#!/usr/bin/env bash
# script to redirect

sudo apt-get update
sudo apt-get -y install nginx
sudo servide nginx start
sudo sh -c "echo 'Holberton School' > /var/www/html/index.html"
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me http
s://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
