#!/usr/bin/env bash
# script to redirect

sudo apt-get update
sudo apt-get -y install nginx
echo -e 'Holberton School' > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/ permanent;' /etc/nginx/sites-available/default
service nginx start
