#!/usr/bin/env bash
# install and config haproxy

apt-get update
apt-get -y install haproxy=1.6.\*
echo -e "backend web_back\n\tbalance roundrobin\n\tserver 1222-web-01 104.196.221.76:80 check\n\tserver 1222-web-02 18.234.234.222:80 check" >> /etc/haproxy/haproxy.cfg
echo -e "frontend web_front\n\tbind *:80\n\tmode http\n\tdefault_backend web_back" >> /etc/haproxy/haproxy.cfg
service haproxy restart
