#!/usr/bin/env bash
# Prints bad lucky and good lucky in 4 & 8
n=0
while ((n < 10))
do
	if ((n == 3))
	then
		echo "bad luck"
	elif ((n == 7))
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	n=$((n+1))
done
